### ISSUE TITLE
Running rust on the K64F

### ISSUE THREAD

**Issue by miker1423** [stefanhoelzl/k64#1]
Hello, I would like to run your crate on my board (a FRDM-K64F), but I'm having a trouble loading the program to the board, can you help me?

**Comment by stefanhoelzl** [comment]
Havent used this crate for a while, doent now whats change in the ecosystem in the meantime.

What is exactly your problem? What are you doing? What are your error messages?

Here are some ressources which might help:
https://rust-embedded.github.io/book/
https://github.com/rust-embedded/cortex-m-quickstart

I had it working on a FRDM-K64F

**Comment by miker1423** [comment]
I think I have a problem with the linker script, given the datasheet, I understand that it has a Flash (Origin = 0x00, Length = 0x100000) 2 SRAM (Upper at Origin = 0x20000000, Length = 0x30000 and Lower at Origin = 0x1fff0000, Length = 0x1000) regions and a FlexRam (Origin = 0x14000000, Length = 0x1000), but I don't know if that regions and addresses are correct.

**Comment by stefanhoelzl** [comment]
this seems right so far (SRAM_L has a length of 0x10000).

to start I would only define the FLASH Region and SRAM_U as the only RAM region.

otherwise you have to tell the linker not to place objects across the border of both ram regions and what sections to place where in which regions!
Since I would assume you do not need all the RAM to begin with, just keep it simple and define only the SRAM_U as your RAM region.

btw:
maybe the Flash region has to start at 0x420, but I cannot remember for sure!
addresses 0x400 until 0x420 are used for flash configurations bits and you do not want to overwrite these! (be careful writing the wrong bits here can lock/brick your chip completely)

**Comment by stefanhoelzl** [comment]
just found my old linker file in my backup
```
MEMORY
{
  /* NOTE K = KiBi = 1024 bytes */
  FLASH : ORIGIN = 0x00000000, LENGTH = 1024K
  RAM : ORIGIN = 0x20000000, LENGTH = 192K
}

/* This is where the call stack will be allocated. */
/* The stack is of the full descending type. */
/* You may want to use this variable to locate the call stack and static
   variables in different memory regions. Below is shown the default value */
_stack_start = ORIGIN(RAM) + LENGTH(RAM);

/* You can use this symbol to customize the location of the .text section */
/* If omitted the .text section will be placed right after the .vector_table
   section */
/* This is required only on microcontrollers that store some configuration right
   after the vector table */
_stext = ORIGIN(FLASH) + 0x800;
```

you have to set `_stext ` to avoid writing the Flash Configuration Bits

**Comment by miker1423** [comment]
Thanks for your linker file, but I think I have another problem than just the linker haha I tried it and it halted again... Do you remember if you used segger for flashing?

**Comment by stefanhoelzl** [comment]
yes i used SEGGER GDB and CLion for flashing and debugging!

**Comment by miker1423** [comment]
Hello! I tried it again today, I used CodeWarrior to load the program to the board (it uses segger underneath), but something weird happend, the debugger said that the board was on a halting state but when I detached the debugger, the red LED (the one next to the debug MCU) was on, showing the halting state, but also the green LED of the RGB LED, which was the purpose of the code, to flash the green LED of the RGB LED. Do you know why this could be happening? My understanding from the behavior is that the code is running to some point, but them it does something that I'm not catching and it halts the MCU. I will upload my code ASAP to be more clear.

**Comment by miker1423** [comment]
The code can be found here (https://github.com/miker1423/test_k64f), I know is basic, and the low power timer can use interrupts, but I want to mess with the least possible variables, and interrupts are a thing that would add complexity.

**Comment by stefanhoelzl** [comment]
have you configured your setup to halt the mcu after loading the program?
I would suggest strip out everything in your program (basically have only a empty main-function).
Configure your setup that the debugger halts your system after loading the program and see how far you can step through.
If you can step to the main-function add some lines of code and repeat.

even with an empty main-function you should be able to step through the startup code of the cortex-m crates

**Comment by miker1423** [comment]
Hello! I finally got it running haha and GDB is gorgeous for debuggin, but I still have a problem, I can't read local variables even when they are still on scope, do you know what could be wrong?

**Comment by stefanhoelzl** [comment]
great!

sorry, but i think I cannot help you there.
